# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
  
def shared_pods
  pod 'FMDB'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Kingfisher'
end

target 'CookingManager' do
  shared_pods

end
